language: python
python:
- 3.6
install:
- pip install tox-travis
- pip install coveralls
deploy:
  provider: pypi
  user: napalmaos
  password:
    secure: UR8IP9Vr+Y14GzTUjV2yp3s350ghrz1qaB4VgBHpVaADdZ0HubOf7h6uXLbT2pkEK9EfwjDd7C+nJBiMUXoz3//W3VxqAeUMEVGl4Ls4SvH0gToHHSnNSacz4RARQJ8XBYfbqKZQjFfUnedbW3b8GYS3RqbDgzvxBBlEZVriEmf8cvE8Cxtpc6I41WCMnt1wfgR/woG6tOnwA/HTDz72SU/kHyYiffuDcq38VzXxj6VVP5MBrOuiad26VIZibikeIOlQgZOUgRpWiRmftY7+ltbWIcFGXe527nCkpPP0WnHBVSG9nJWGobat1MiM5RsRo/mwvbXx1Y9uf+KAwjQQDMt2Wzb+lA7v1/4K53XLxwsq1iqHxq6GyFV+kGKPbu7SoylUkBUCJavpx/af+ChLs/1fyh3yYeQSx6tsm8TXPoH1xTBnzH0r53sK2j+ElxUM2/zl96yGINL2SoyFNxwszkGcA/Q6Y1znr0rUGjgfLQF4d6Iys9+ejoUtrMcEKlwbUtqmDxqruZgSLJxawSNUJfFLmySEiF1usB+Y+fB9LK/kCrjQZ4aAzc1GQy9ITvBJ2SARtgxV/nN1anQ/nFA1ZsnHgYKQkHjftFAovQnP17SMdrY0uHWNIkoU5qm+MFPdbFjL7keJN72ZHEXodwK5iUsi5tGxnpOUZe9ML1jf//k=
  on:
    tags: true
    branch: master
script:
- tox
after_success:
- coveralls
